name: tool_mobile
description: Flutter Tools' base plus mobile. Use to create command line tools.
version: 1.9.5+1
homepage: https://github.com/mmcc007/tool_mobile
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  tool_base:
    git: https://github.com/satsuma0711/tool_base.git

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^5.2.0